pipeline {
    agent any
    
    environment {
        REPO_URL= 'https://github.com/Asaf01/ci'
        CONTAINER_NAME = "wordpress"
        IMAGE_NAME = 'wordpress'
        
    }
 
    stages{
        stage("clone"){
            steps{
                
                sh 'pwd'
                sh 'docker build -t "wordpress"' .
                sh 'docker images '
     }
               }   
         }
               }